# This job is to test different maven profiles in sdk branch again Pull Request raised
# This workflow targets Java with Maven execution

name: TestNG Repo Java 11 - Ubuntu Sample

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The full commit id to build'
        required: true

jobs:
  test-java-11-ubuntu:
    runs-on: ubuntu-latest
    name: TestNG Repo Java 11 - Ubuntu Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}
          token: ${{ secrets.TOKEN }} # Assuming you have created and set up the secret GH_TOKEN

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run mvn test
        run: |
          mvn compile
          mvn test

      - name: Run mvn profile sample-local-test
        run: |
          mvn compile
          mvn test -P sample-local-test

      - name: Run mvn profile sample-test
        run: |
          mvn compile
          mvn test -P sample-test

      - name: Set job status to completed
        if: always()
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: status-check-completed
        env:
          conclusion: ${{ job.status }}
          commit_sha: ${{ github.event.inputs.commit_sha }}
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const result = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'TestNG Repo Java 11 - Ubuntu Sample',
              head_sha: process.env.commit_sha,
              status: 'completed',
              conclusion: process.env.conclusion
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The status-check response : ${result.status} Response : ${JSON.stringify(result.response)}`)
            if (result.status !== 201) {
              console.log('Failed to create check run')
            }
