name: TestNG SDK Test workflow for Maven on workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The full commit id to build'
        required: true

jobs:
  comment-run:
    runs-on: ubuntu-latest
    
    name: TestNG Repo Java 17 - Ubuntu Sample
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Run mvn test
        run: |
          mvn compile
          mvn test
          
      - name: Run mvn profile sample-local-test
        run: |
          mvn compile
          mvn test -P sample-local-test
          
      - name: Run mvn profile sample-test
        run: |
          mvn compile
          mvn test -P sample-test
          
      - name: Set workflow status to completed
        if: always()
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        with:
          github-token: ${{ github.token }}
          script: |
            const result = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'TestNG Repo Java 17 - Ubuntu Sample',
              head_sha: context.sha,
              status: 'completed'
            }).catch((err) => ({status: err.status, response: err.response}));
            console.log(`The status-check response: ${result.status} Response: ${JSON.stringify(result.response)}`);
            if (result.status !== 201) {
              console.log('Failed to create check run');
            }
